"use client";

import { X, Download, Sparkles, TrendingUp, CheckCircle, Quote, Star, Layers, Calendar, User } from "lucide-react";
import { Report } from "@/types/report";
import SentimentBadge from "@/components/feedback/SentimentBadge";

interface VoCReportModalProps {
  report: Report | null;
  open: boolean;
  onClose: () => void;
  onDownload: (report: Report) => void;
}

export default function VoCReportModal({
  report,
  open,
  onClose,
  onDownload,
}: VoCReportModalProps) {
  if (!open || !report) return null;

  const stats = report.stats;

  return (
    <>
      {/* Overlay */}
      <div
        className="fixed inset-0 z-50 bg-black/40 backdrop-blur-xs transition-opacity"
        onClick={onClose}
      />

      {/* Modal Container */}
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        <div className="flex max-h-[90vh] w-full max-w-4xl flex-col rounded-3xl bg-white shadow-2xl overflow-hidden border border-loop-border animate-in fade-in zoom-in-95 duration-200">
          
          {/* Header */}
          <div className="flex items-center justify-between border-b border-loop-border px-6 py-5 bg-cream">
            <div className="flex items-center gap-3.5">
              <div className="rounded-2xl bg-forest p-3 text-amber-400 shadow-md">
                <Sparkles size={24} />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded-full bg-emerald-100 border border-emerald-300 px-2.5 py-0.5 text-[10px] font-bold text-emerald-800 uppercase tracking-wider">
                    AI Voice-of-Customer Report
                  </span>
                </div>
                <h2 className="text-xl font-bold text-forest mt-0.5">
                  {report.name}
                </h2>
              </div>
            </div>

            <button
              onClick={onClose}
              className="rounded-xl p-2 text-slate-400 hover:bg-white hover:text-slate-700 transition"
            >
              <X size={20} />
            </button>
          </div>

          {/* Report Body */}
          <div className="flex-1 overflow-y-auto p-6 space-y-6">
            
            {/* Metadata Bar */}
            <div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-slate-50 border border-slate-200 p-4 text-xs font-medium text-slate-600">
              <div className="flex items-center gap-2">
                <User size={15} className="text-sage" />
                <span>Generated By: <strong className="text-forest">{report.createdBy}</strong></span>
              </div>
              <div className="flex items-center gap-2">
                <Calendar size={15} className="text-sage" />
                <span>Date: <strong className="text-forest">{report.createdAt}</strong></span>
              </div>
              <div className="flex items-center gap-2">
                <TrendingUp size={15} className="text-amber-600" />
                <span>Sentiment Shift: <strong className="text-emerald-700">{stats?.sentimentShift || "Stable"}</strong></span>
              </div>
            </div>

            {/* Pre-Computed Key Metrics Grid */}
            {stats && (
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                <div className="rounded-2xl border border-loop-border bg-white p-4 text-center shadow-xs">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-taupe block">Total Feedback</span>
                  <span className="text-2xl font-extrabold text-forest mt-1 block">{stats.totalCount}</span>
                  <span className="text-[10px] text-slate-400 font-medium">100% Ingested</span>
                </div>

                <div className="rounded-2xl border border-emerald-100 bg-emerald-50/50 p-4 text-center shadow-xs">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-800 block">Positive Sentiment</span>
                  <span className="text-2xl font-extrabold text-emerald-700 mt-1 block">{stats.positiveRate}%</span>
                  <span className="text-[10px] text-emerald-600 font-medium">{stats.positiveCount} items</span>
                </div>

                <div className="rounded-2xl border border-amber-100 bg-amber-50/50 p-4 text-center shadow-xs">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-amber-800 block">Average Rating</span>
                  <span className="text-2xl font-extrabold text-amber-700 mt-1 block">{stats.avgRating} / 5.0</span>
                  <span className="text-[10px] text-amber-600 font-medium">Customer Score</span>
                </div>

                <div className="rounded-2xl border border-red-100 bg-red-50/50 p-4 text-center shadow-xs">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-red-800 block">Negative Reports</span>
                  <span className="text-2xl font-extrabold text-red-700 mt-1 block">{stats.negativeRate}%</span>
                  <span className="text-[10px] text-red-600 font-medium">{stats.negativeCount} items</span>
                </div>
              </div>
            )}

            {/* Top Themes Section */}
            {stats?.topThemes && stats.topThemes.length > 0 && (
              <div className="rounded-2xl border border-loop-border bg-white p-5 shadow-xs space-y-3">
                <div className="flex items-center gap-2">
                  <Layers size={18} className="text-forest" />
                  <h3 className="text-xs font-bold uppercase tracking-wider text-forest">
                    Top Identified Feedback Themes
                  </h3>
                </div>

                <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2.5">
                  {stats.topThemes.map((t, idx) => (
                    <div
                      key={idx}
                      className="flex items-center justify-between rounded-xl bg-cream/40 border border-loop-border p-3 text-xs"
                    >
                      <span className="font-bold text-forest">{t.theme}</span>
                      <div className="flex items-center gap-1.5">
                        <span className="rounded-full bg-forest/10 px-2 py-0.5 font-bold text-forest text-[10px]">
                          {t.count} items
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Representative Real Quotes Section */}
            {stats?.realQuotes && stats.realQuotes.length > 0 && (
              <div className="rounded-2xl border border-loop-border bg-white p-5 shadow-xs space-y-3">
                <div className="flex items-center gap-2">
                  <Quote size={18} className="text-amber-500" />
                  <h3 className="text-xs font-bold uppercase tracking-wider text-forest">
                    Representative Customer Voice Quotes
                  </h3>
                </div>

                <div className="space-y-3">
                  {stats.realQuotes.map((q, idx) => (
                    <div
                      key={idx}
                      className="rounded-xl border border-slate-100 bg-slate-50/60 p-3.5 text-xs space-y-2"
                    >
                      <div className="flex items-center justify-between">
                        <span className="font-bold text-forest">{q.customer} ({q.category})</span>
                        <div className="flex items-center gap-2">
                          <SentimentBadge sentiment={q.sentiment as "Positive" | "Neutral" | "Negative"} />
                          <span className="flex items-center font-bold text-amber-600 text-[10px]">
                            <Star size={10} className="fill-amber-400 stroke-amber-500 mr-0.5" />
                            {q.rating}/5
                          </span>
                        </div>
                      </div>

                      <p className="text-slate-700 italic bg-white p-2.5 rounded-lg border border-slate-200 leading-relaxed">
                        &ldquo;{q.message}&rdquo;
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* AI Executive Narrative Summary */}
            {report.narrative && (
              <div className="rounded-2xl border border-sage/30 bg-sage-bg/30 p-5 shadow-xs space-y-3">
                <div className="flex items-center gap-2 text-forest font-bold text-sm">
                  <Sparkles size={16} className="text-amber-500" />
                  <span>Executive AI Commentary (Bounded by Real Metrics)</span>
                </div>
                <div className="text-xs leading-relaxed text-forest-mid whitespace-pre-wrap font-sans bg-white/70 p-4 rounded-xl border border-sage/20">
                  {report.narrative}
                </div>
              </div>
            )}

            {/* Actionable Recommendations */}
            {stats?.recommendedActions && stats.recommendedActions.length > 0 && (
              <div className="rounded-2xl border border-emerald-200 bg-emerald-50/40 p-5 shadow-xs space-y-3">
                <div className="flex items-center gap-2 font-bold text-emerald-900 text-sm">
                  <CheckCircle size={16} className="text-emerald-600" />
                  <span>Recommended Action Plan</span>
                </div>

                <ul className="space-y-2 text-xs text-slate-800">
                  {stats.recommendedActions.map((action, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-emerald-600 text-[10px] font-bold text-white">
                        {idx + 1}
                      </span>
                      <span className="mt-0.5 font-medium">{action}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

          </div>

          {/* Footer Actions */}
          <div className="border-t border-loop-border px-6 py-4 bg-cream flex items-center justify-between">
            <button
              onClick={onClose}
              className="rounded-xl border border-loop-border px-5 py-2 text-xs font-semibold text-slate-600 hover:bg-cream-dark transition"
            >
              Close
            </button>

            <button
              onClick={() => onDownload(report)}
              className="inline-flex items-center gap-2 rounded-xl bg-forest px-6 py-2.5 text-xs font-semibold text-champagne hover:bg-forest-mid hover:text-white transition shadow-sm"
            >
              <Download size={15} />
              <span>Export PDF / Text Report</span>
            </button>
          </div>

        </div>
      </div>
    </>
  );
}
