"use client";

import { useEffect, useMemo, useState } from "react";

import ReportsHeader from "@/components/reports/ReportsHeader";
import ReportCards from "@/components/reports/ReportCards";
import ReportFilters from "@/components/reports/ReportFilters";
import ReportTable from "@/components/reports/ReportTable";
import ReportPagination from "@/components/reports/ReportPagination";
import GenerateReportModal from "@/components/reports/GenerateReportModal";
import ViewReportModal from "@/components/reports/ViewReportModal";
import EmptyReports from "@/components/reports/EmptyReports";

import { Report } from "@/types/report";
import { reportService } from "@/services/report.service";
import { authService } from "@/services/auth.service";

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);

  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [format, setFormat] = useState("");

  const [modalOpen, setModalOpen] = useState(false);
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);
  const [viewModalOpen, setViewModalOpen] = useState(false);

  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 10;

  useEffect(() => {
    async function loadReports() {
      const data = await reportService.getReports();
      setReports(data);
    }
    loadReports();
  }, []);

  const filteredReports = useMemo(() => {
    return reports.filter((report) => {
      const matchesSearch =
        report.name.toLowerCase().includes(search.toLowerCase()) ||
        report.description.toLowerCase().includes(search.toLowerCase());

      const matchesStatus = !status || report.status === status;
      const matchesFormat = !format || report.format === format;

      return matchesSearch && matchesStatus && matchesFormat;
    });
  }, [reports, search, status, format]);

  const totalPages = Math.max(1, Math.ceil(filteredReports.length / pageSize));

  const paginatedReports = filteredReports.slice(
    (currentPage - 1) * pageSize,
    currentPage * pageSize
  );

  async function handleGenerate(data: {
    name: string;
    description: string;
    format: "PDF" | "Excel" | "CSV";
  }) {
    const currentUser = authService.getCurrentUser();
    const newReport = await reportService.generateReport({
      name: data.name,
      description: data.description || "Custom feedback and sentiment report.",
      format: data.format,
      status: "Generated",
      createdBy: currentUser?.name || "Administrator",
      downloadUrl: `/reports/${data.name.toLowerCase().replace(/\s+/g, "-")}.${data.format.toLowerCase()}`,
    });

    setReports((prev) => [newReport, ...prev]);
    setModalOpen(false);
  }

  function handleView(report: Report) {
    setSelectedReport(report);
    setViewModalOpen(true);
  }

  function handleDownload(report: Report) {
    const content = `LOOP AI REPORT: ${report.name}
==================================================
Date: ${report.createdAt}
Created By: ${report.createdBy}
Format: ${report.format}
Status: ${report.status}

Description:
${report.description}

EXECUTIVE SUMMARY & KEY INSIGHTS:
- Total Customer Feedback Analyzed: 1,540 entries
- Overall Positive Sentiment: 78%
- Top Feedback Category: Product Experience & Performance
- Recommendation: Prioritize mobile UI responsiveness and query latency optimizations.

Generated by LOOP AI Platform.
`;

    const mimeType = report.format === "CSV" ? "text/csv" : "text/plain";
    const blob = new Blob([content], { type: `${mimeType};charset=utf-8;` });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    const fileExt = report.format === "Excel" ? "xlsx" : report.format.toLowerCase();
    link.download = `${report.name.toLowerCase().replace(/\s+/g, "-")}.${fileExt}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  async function handleDelete(report: Report) {
    await reportService.deleteReport(report.id);
    setReports((prev) => prev.filter((r) => r.id !== report.id));
    if (selectedReport?.id === report.id) {
      setViewModalOpen(false);
      setSelectedReport(null);
    }
  }

  return (
    <>
      <div className="space-y-8">
        <ReportsHeader onGenerate={() => setModalOpen(true)} />

        <ReportCards reports={reports} />

        <ReportFilters
          search={search}
          onSearchChange={setSearch}
          status={status}
          onStatusChange={setStatus}
          format={format}
          onFormatChange={setFormat}
          onGenerate={() => setModalOpen(true)}
        />

        {filteredReports.length === 0 ? (
          <EmptyReports onGenerate={() => setModalOpen(true)} />
        ) : (
          <>
            <ReportTable
              reports={paginatedReports}
              onView={handleView}
              onDownload={handleDownload}
              onDelete={handleDelete}
            />

            <ReportPagination
              currentPage={currentPage}
              totalPages={totalPages}
              totalItems={filteredReports.length}
              pageSize={pageSize}
              onPageChange={setCurrentPage}
            />
          </>
        )}
      </div>

      <GenerateReportModal
        open={modalOpen}
        onClose={() => setModalOpen(false)}
        onGenerate={handleGenerate}
      />

      <ViewReportModal
        report={selectedReport}
        open={viewModalOpen}
        onClose={() => {
          setViewModalOpen(false);
          setSelectedReport(null);
        }}
        onDownload={handleDownload}
      />
    </>
  );
}